### ISSUE TITLE
[Help] Arch + Gnome + Wayland, unable to run 

### ISSUE THREAD

**Issue by dougg0k** [mdgaziur/findex#63]
Hi,

I am using a Arch + Gnome + Wayland, but I am unable to run this tool.

In the readme, you say that wayland cannot bind that key and suggest to add the number 1 to that file. It doesnt really tell anything.

After typing `findex-daemon` in the terminal, the second time, it says that it is running, but it gives the not found status for the service.

```
nu ❯ sudo systemctl status findex-daemon.service
Unit findex-daemon.service could not be found.
```

When I type `findex` it says that it is listening to a hotkey, I type the `shift + space` that are included in the `config.toml` file, but nothing happens and nothing opens.

Can you provide better clarity in the instructions in how to make this tool work?

Thanks.

**Comment by mdgaziur** [comment]
The readme suggests that you bind the command `echo 1 > ~/.config/findex/toggle_file` to your desired hotkey. Like, when you press the hotkey, the command is run. Hopefully things are clear now

**Comment by dougg0k** [comment]
What is the pattern though to set any sort of keybinding combination? `<Super>` or `Super_L` or just `Super`.

What about the second keybinding, does it concat with a plus or some other way?

**Comment by mdgaziur** [comment]
Ummm, if you're setting the hotkey from your DE then you don't have to touch the `config.toml` file. 
Anyways, the pattern is `<Super>`. So, Super+L would be `<Super>L`.

**Comment by dougg0k** [comment]
```
nu ✗ cat ~/.config/findex/toggle_file | to text
<Shift>a
                                                                                                                                                                                                  
nu ❯ findex
[INFO] Starting Findex...
[INFO] listening for hotkey...
AAAAAA
```

And nothing, what am I doing wrong? 

Same if I set `<Super>a`

**Comment by mdgaziur** [comment]
Here's how the thing works:
- Findex watches `~/.config/findex/toggle_file` for changes when run in Wayland.
- When a change is detected, Findex treats it as hotkey trigger.
You can check this right now by starting Findex first and then running `echo 1 > ~/.config/findex/toggle_file`. Findex should open after you run that command.

You are supposed to bind a hotkey in your Desktop Environment by setting a shortcut key that runs the command when triggered. 

I'm on KDE so I can't show it's done on Gnome. But the screenshots should give you a rough idea:

1. ![image](https://github.com/user-attachments/assets/f54a1dd4-85ce-445c-b6b0-1a000574e932)
2. ![image](https://github.com/user-attachments/assets/02b626fb-1a57-436c-bad3-8f036b6c2efb)
 
For a more detailed steps on how you can achieve this on Gnome, check this: https://docs.fedoraproject.org/en-US/quick-docs/gnome-setting-key-shortcut/
It shouldn't matter that this doc is from Fedora because Gnome is same regardless of the distro you are using.

**Comment by dougg0k** [comment]
isnt there a way to just call the bin and be done with it?

**Comment by mdgaziur** [comment]
Unfortunately, no. You can create a shell script containing the command in `/usr/bin`. Let's say, you saved it as `findex_toggle`. Now running `findex_toggle` from terminal should launch Findex.

The shell script may look like this:

```sh
#! /bin/sh

echo 1 > ~/.config/findex/toggle_file
```

**Comment by dougg0k** [comment]
Right
